apiVersion: v1
kind: service 
metadata:
 name: result-service
 label:
  name: result-service
  app: demo-result-app

spec:
 type: LoadBalancer
 ports:
 - port: 80
   targetPort: 80
 selector:
  name: result-app-pod
  app: demo-result-app